---
- name: Create SSH directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory

- name: Build SSH config
  template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0755
    force: yes
  when: sshconfig_hosts is defined
